# Contains service definitions that extend the application configuration and help generate the final webpack-
# configuration file.
services:
    hostnet_webpack.config.output:
        class: Hostnet\Component\WebpackBundle\Configuration\Config\OutputConfig
        tags:
            - { name: hostnet_webpack.config_extension }

    hostnet_webpack.config.resolve:
        class: Hostnet\Component\WebpackBundle\Configuration\Config\ResolveConfig
        tags:
            - { name: hostnet_webpack.config_extension }

    hostnet_webpack.config.resolve_loader:
        class: Hostnet\Component\WebpackBundle\Configuration\Config\ResolveLoaderConfig
        tags:
            - { name: hostnet_webpack.config_extension }
