services:

    hostnet_webpack.plugin.define:
        class: Hostnet\Component\WebpackBridge\Configuration\Plugin\DefinePlugin
        tags:
            - { name: hostnet_webpack.config_extension }
