imports:
    - { resource: config.yml }
    - { resource: loaders.yml }
    - { resource: plugins.yml }

services:

    hostnet_webpack.bridge.generate_config_command:
        class: Hostnet\Bundle\WebpackBundle\Command\CompileCommand
        arguments:
            - '@hostnet_webpack.bridge.asset_compiler'
            - '@hostnet_webpack.bridge.asset_dumper'
            - '@logger'
            - '@hostnet_webpack.bridge.profiler'
            - []
        tags:
            - { name: console.command }

    hostnet_webpack.bridge.config_generator:
        class: Hostnet\Component\Webpack\Configuration\ConfigGenerator

    hostnet_webpack.bridge.asset_tracker:
        class: Hostnet\Component\Webpack\Asset\Tracker
        arguments:
            - '@hostnet_webpack.bridge.profiler'
            - '@templating.finder'
            - '%kernel.cache_dir%'
            - '%kernel.root_dir%'
            - '' # asset_path
            - [] # bundles

    hostnet_webpack.bridge.asset_dumper:
        class: Hostnet\Component\Webpack\Asset\Dumper
        arguments:
            - '@logger'
            - [] # bundles
            - '' # 'public' dir
            - '' # output dir

    hostnet_webpack.bridge.compiler_process:
        class: Symfony\Component\Process\Process
        arguments:
            - '' # Node binary
            - '' # Cache directory

    hostnet_webpack.bridge.asset_twig_parser:
        class: Hostnet\Component\Webpack\Asset\TwigParser
        arguments:
            - '@hostnet_webpack.bridge.asset_tracker'
            - '@twig'
            - '%kernel.cache_dir%'

    hostnet_webpack.bridge.asset_compiler:
        class: Hostnet\Component\Webpack\Asset\Compiler
        arguments:
            - '@hostnet_webpack.bridge.profiler'
            - '@hostnet_webpack.bridge.asset_tracker'
            - '@hostnet_webpack.bridge.asset_twig_parser'
            - '@hostnet_webpack.bridge.config_generator'
            - '@hostnet_webpack.bridge.compiler_process'
            - '%kernel.cache_dir%'
            - [] # bundles
            - '@?debug.stopwatch'

    hostnet_webpack.bridge.twig_extension:
        class: Hostnet\Bundle\WebpackBundle\Twig\TwigExtension
        arguments:
            - '' # public_path
            - '' # dump_path
        tags:
            - { name: twig.extension }

    hostnet_webpack.bridge.profiler:
        class: Hostnet\Component\Webpack\Profiler\Profiler
        tags:
            - { name: data_collector, template: "WebpackBundle::profiler.html.twig", id: "webpack" }
